- name: installing java
  yum:
    name: "{{ java_version_rhel }}"
    state: present

- name: updating java version
  command: "sudo update-alternatives --set java /usr/lib/jvm/java-{{ java_version }}-amazon-corretto.x86_64/bin/java"

